# Generated by Django 4.1 on 2022-08-14 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_project1', '0002_teachermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherModel',
        ),
    ]
