# Generated by Django 4.1 on 2022-08-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_project1', '0003_delete_teachermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrievanceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='attachments')),
                ('stars', models.IntegerField(default=0)),
                ('is_answered', models.BooleanField(default=False)),
                ('reply', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='is_staff',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
