# Generated by Django 4.1 on 2022-08-14 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_project1', '0005_alter_grievancedata_email_alter_grievancedata_reply_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
        migrations.RemoveField(
            model_name='grievancedata',
            name='image',
        ),
    ]
